import type { PropertyRecord, FibraPortfolio, WalletState, Notification } from "./types";

export const mockProperties: PropertyRecord[] = [
  {
    id: "prop-001",
    tokenId: "#4721",
    title: "Residencial Torre Polanco",
    location: "Polanco, CDMX",
    area: 185,
    cadastralKey: "CAT-09-016-001",
    price: 245,
    priceUSD: 8575,
    image: "/images/property-1.jpg",
    contractHash: "0x7a3b...8F2e",
    registrationDate: "2025-03-15",
    status: "certified",
    type: "apartment",
    logEntries: [
      { date: "2025-03-15", action: "Registro inicial on-chain", txHash: "0xabc...123" },
      { date: "2025-04-02", action: "Certificado libre de adeudos", txHash: "0xdef...456" },
      { date: "2025-05-10", action: "Remodelacion verificada", txHash: "0xghi...789" },
    ],
  },
  {
    id: "prop-002",
    tokenId: "#4722",
    title: "Casa Colonial San Angel",
    location: "San Angel, CDMX",
    area: 320,
    cadastralKey: "CAT-09-010-047",
    price: 480,
    priceUSD: 16800,
    image: "/images/property-2.jpg",
    contractHash: "0x3e1f...B9a4",
    registrationDate: "2025-01-20",
    status: "escrow-active",
    type: "house",
    logEntries: [
      { date: "2025-01-20", action: "Registro inicial on-chain", txHash: "0xjkl...012" },
      { date: "2025-02-15", action: "Escrow iniciado", txHash: "0xmno...345" },
    ],
  },
  {
    id: "prop-003",
    tokenId: "#4723",
    title: "Penthouse Santa Fe Elite",
    location: "Santa Fe, CDMX",
    area: 420,
    cadastralKey: "CAT-09-008-112",
    price: 890,
    priceUSD: 31150,
    image: "/images/property-3.jpg",
    contractHash: "0x9c2d...E7f1",
    registrationDate: "2024-11-08",
    status: "certified",
    type: "penthouse",
    logEntries: [
      { date: "2024-11-08", action: "Registro inicial on-chain", txHash: "0xpqr...678" },
      { date: "2025-01-12", action: "Inspeccion estructural OK", txHash: "0xstu...901" },
      { date: "2025-03-20", action: "Certificado de energia", txHash: "0xvwx...234" },
    ],
  },
  {
    id: "prop-004",
    tokenId: "#4724",
    title: "Residencia Coyoacan Verde",
    location: "Coyoacan, CDMX",
    area: 275,
    cadastralKey: "CAT-09-003-089",
    price: 310,
    priceUSD: 10850,
    image: "/images/property-4.jpg",
    contractHash: "0x5f8a...C3d2",
    registrationDate: "2025-02-28",
    status: "presale",
    type: "house",
    logEntries: [
      { date: "2025-02-28", action: "Registro inicial on-chain", txHash: "0xyz1...567" },
    ],
  },
  {
    id: "prop-005",
    tokenId: "#4725",
    title: "Oficinas Reforma Centro",
    location: "Paseo de la Reforma, CDMX",
    area: 550,
    cadastralKey: "CAT-09-015-203",
    price: 1200,
    priceUSD: 42000,
    image: "/images/property-5.jpg",
    contractHash: "0x1a7b...D5e9",
    registrationDate: "2024-09-15",
    status: "debts-validated",
    type: "commercial",
    logEntries: [
      { date: "2024-09-15", action: "Registro inicial on-chain", txHash: "0xab2...890" },
      { date: "2024-12-01", action: "Adeudo predial liquidado", txHash: "0xcd3...123" },
      { date: "2025-01-30", action: "Validacion adeudos completa", txHash: "0xef4...456" },
    ],
  },
  {
    id: "prop-006",
    tokenId: "#4726",
    title: "Villa Riviera Cancun",
    location: "Zona Hotelera, Cancun",
    area: 380,
    cadastralKey: "CAT-23-001-045",
    price: 650,
    priceUSD: 22750,
    image: "/images/property-6.jpg",
    contractHash: "0x8b4c...A1f3",
    registrationDate: "2025-04-05",
    status: "certified",
    type: "villa",
    logEntries: [
      { date: "2025-04-05", action: "Registro inicial on-chain", txHash: "0xgh5...789" },
      { date: "2025-04-20", action: "Certificado libre de adeudos", txHash: "0xij6...012" },
    ],
  },
];

export const mockFibras: FibraPortfolio[] = [
  {
    id: "fibra-001",
    name: "FIBRA Desarrollo Norte CDMX",
    symbol: "LDR-NORTE",
    apy: 12.5,
    funded: 2800,
    target: 5000,
    pricePerToken: 0.25,
    properties: ["prop-001", "prop-003"],
    propertyCount: 2,
    description: "Portafolio diversificado de desarrollos premium en la zona norte de la Ciudad de Mexico con retornos proyectados superiores al mercado.",
    status: "funding",
  },
  {
    id: "fibra-002",
    name: "FIBRA Retorno Residencial",
    symbol: "LDR-RES",
    apy: 9.8,
    funded: 4200,
    target: 4500,
    pricePerToken: 0.15,
    properties: ["prop-002", "prop-004", "prop-006"],
    propertyCount: 3,
    description: "Fondo residencial enfocado en propiedades con alta demanda de renta y plusvalia comprobada en zonas de alto valor.",
    status: "funding",
  },
  {
    id: "fibra-003",
    name: "FIBRA Comercial Premium",
    symbol: "LDR-COM",
    apy: 15.2,
    funded: 8000,
    target: 8000,
    pricePerToken: 0.50,
    properties: ["prop-005"],
    propertyCount: 1,
    description: "Portafolio de activos comerciales de alta gama sobre Paseo de la Reforma con contratos de arrendamiento a largo plazo.",
    status: "active",
  },
  {
    id: "fibra-004",
    name: "FIBRA Turismo Caribe",
    symbol: "LDR-CARIBE",
    apy: 18.3,
    funded: 1200,
    target: 6000,
    pricePerToken: 0.10,
    properties: ["prop-006"],
    propertyCount: 1,
    description: "Inversion en propiedades turisticas de la Riviera Maya y Zona Hotelera de Cancun con rendimientos estacionales elevados.",
    status: "funding",
  },
];

export const mockWallet: WalletState = {
  connected: false,
  address: "0x7a3b9E...4F2e",
  balanceAVAX: 24.738,
  balanceLadrillos: 1250,
  fibraParticipations: 3,
  recentTx: [
    { id: "tx-1", type: "ICM Message", description: "ICM Message Received", amount: "0.00 AVAX", timestamp: "hace 2 min" },
    { id: "tx-2", type: "Escrow", description: "Escrow Funded", amount: "245 AVAX", timestamp: "hace 15 min" },
    { id: "tx-3", type: "Dividendo", description: "Dividendo FIBRA Recibido", amount: "1.25 AVAX", timestamp: "hace 1 hora" },
  ],
};

export const mockNotifications: Notification[] = [
  { id: "n-1", message: "Tokenizacion exitosa - Prop #4726", type: "success", timestamp: "hace 5 min" },
  { id: "n-2", message: "Dividendo recibido: 1.25 AVAX", type: "info", timestamp: "hace 1 hora" },
  { id: "n-3", message: "Escrow #4722 pendiente de verificacion", type: "warning", timestamp: "hace 3 horas" },
];
